### ISSUE TITLE
Compilation error with Coq 8.16.0

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/entree-specs#1]
`entree-specs` (as of commit bfdeb7360d572522e6710f99cd1c50ceccc46bff) builds with Coq 8.15.2 and earlier, but fails to build with Coq 8.16.0:

```
$ make
<elided>
COQC theories/Core/EnTreeDefinition.v
COQC theories/Eq/Eqit.v
COQC theories/Core/SubEvent.v
COQC theories/Ref/Padded.v
COQC theories/Ref/EnTreeSpecDefinition.v
COQC theories/Ref/MRecSpec.v
COQC theories/Ref/EnTreeSpecFacts.v
File "./theories/Ref/EnTreeSpecFacts.v", line 735, characters 31-49:
Error: Cannot find an homogeneous relation to rewrite.

make[1]: *** [Makefile.coq:793: theories/Ref/EnTreeSpecFacts.vo] Error 1
make: *** [Makefile.coq:409: all] Error 2
```

The failing line is here:

https://github.com/GaloisInc/entree-specs/blob/bfdeb7360d572522e6710f99cd1c50ceccc46bff/theories/Ref/EnTreeSpecFacts.v#L735

**Comment by pennyannn** [comment]
Run into a similar [issue](https://productionresultssa4.blob.core.windows.net/actions-results/69ede1db-1c67-4c48-9b1d-00de98f2ded1/workflow-job-run-eadd520b-eef4-5c25-4e9f-d2e88087df37/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-11-11T23%3A03%3A04Z&sig=zXw6FTew5RYRzc8et%2BtkRwde0AL4BdLJRVo7d0VHlZA%3D&ske=2024-11-12T10%3A32%3A22Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-11-11T22%3A32%3A22Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-08-04&sp=r&spr=https&sr=b&st=2024-11-11T22%3A52%3A59Z&sv=2024-08-04) in AWS-LC-verification CI. The error output:
```
entree-specs is now pinned to git+https://github.com/GaloisInc/entree-specs.git#52c4868f1f65c7ce74e90000214de27e23ba98fb (version dev)
2024-11-11T22:49:31.4310095Z #12 380.5 
2024-11-11T22:49:35.9661115Z #12 385.2 The following actions will be performed:
2024-11-11T22:49:35.9662177Z #12 385.2   - install entree-specs dev*
2024-11-11T22:49:36.1169597Z #12 385.2 
2024-11-11T22:49:36.1170177Z #12 385.2 <><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2024-11-11T22:49:44.3943045Z #12 393.6 [ERROR] The compilation of entree-specs failed at "/usr/bin/make".
2024-11-11T22:49:44.3943796Z #12 393.6 
2024-11-11T22:49:44.3944371Z #12 393.6 #=== ERROR while compiling entree-specs.dev ===================================#
2024-11-11T22:49:44.3945939Z #12 393.6 # context              2.0.5 | linux/x86_64 | ocaml-system.4.08.1 | pinned(git+https://github.com/GaloisInc/entree-specs.git#52c4868f1f65c7ce74e90000214de27e23ba98fb#52c4868f)
2024-11-11T22:49:44.3947324Z #12 393.6 # path                 ~/.opam/default/.opam-switch/build/entree-specs.dev
2024-11-11T22:49:44.3947886Z #12 393.6 # command              /usr/bin/make
2024-11-11T22:49:44.3948289Z #12 393.6 # exit-code            2
2024-11-11T22:49:44.3948783Z #12 393.6 # env-file             ~/.opam/log/entree-specs-27116-2dea01.env
2024-11-11T22:49:44.3949437Z #12 393.6 # output-file          ~/.opam/log/entree-specs-27116-2dea01.out
2024-11-11T22:49:44.3949944Z #12 393.6 ### output ###
2024-11-11T22:49:44.3950229Z #12 393.6 # [...]
2024-11-11T22:49:44.3950545Z #12 393.6 # COQC theories/Core/EnTreeDefinition.v
2024-11-11T22:49:44.3950955Z #12 393.6 # COQC theories/Eq/Eqit.v
2024-11-11T22:49:44.3951331Z #12 393.6 # COQC theories/Core/SubEvent.v
2024-11-11T22:49:44.3951717Z #12 393.6 # COQC theories/Ref/Padded.v
2024-11-11T22:49:44.3952140Z #12 393.6 # COQC theories/Ref/EnTreeSpecDefinition.v
2024-11-11T22:49:44.3952582Z #12 393.6 # COQC theories/Ref/MRecSpec.v
2024-11-11T22:49:44.3953001Z #12 393.6 # COQC theories/Ref/EnTreeSpecFacts.v
2024-11-11T22:49:44.3953585Z #12 393.6 # File "./theories/Ref/EnTreeSpecFacts.v", line 432, characters 60-101:
2024-11-11T22:49:44.3954281Z #12 393.6 # Error: No such goal. The current bullet * is unfinished.
2024-11-11T22:49:44.3954937Z #12 393.6 # 
2024-11-11T22:49:44.3956225Z #12 393.6 # make[1]: *** [Makefile.coq:764: theories/Ref/EnTreeSpecFacts.vo] Error 1
2024-11-11T22:49:44.3957080Z #12 393.6 # make: *** [Makefile.coq:387: all] Error 2
```
But this is with coq.8.15.1, so I'm not sure what is going on. The CI used to be passing with this version of Coq and entree-specs is pinned to be #52c4868f.

**Comment by sauclovian-g** [comment]
That is entree-specs #7, so you should be able to fix it by updating.

**Comment by sauclovian-g** [comment]
(alternatively you could restrict coq-paco to 4.2.0, but updating's probably preferable in the long run)

**Comment by pennyannn** [comment]
Thanks for the pointers! I will try updating entree-specs.
